### ISSUE TITLE
Can't Pull Docker Image

### ISSUE THREAD

**Issue by lmuller18** [drod3763/kiliman-operator-mono-lig-docker#4]
Trying to pull this docker image results in an access denied error:

```
Error response from daemon: pull access denied for d3763/operator-mono-lig, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by drod3763** [comment]
This isn't hosted on dockerhub. You have to clone it using git and follow the rest of the README

**Comment by lmuller18** [comment]
I had done that but was running into some errors so I tried pulling directly. Now that #3 got merged in, everything looks to be working great.  Thanks!

**Comment by drod3763** [comment]
#3 uses release 2.2.8. I've made another commit since then that should work for 2.4.1 now. Feel free to pull and rebuild.

**Comment by lmuller18** [comment]
TY. Upgraded and installed. Some ligatures still aren't working in some files but it seems to be the theme I'm using in VSCode. The actual ligatures from the font seem to be working fine now in other programs / themes after the update. Thanks!
